### ISSUE TITLE
The Datepicker & Timepicker is not working with ModelForms

### ISSUE THREAD

**Issue by samirtendulkar** [monim67/django-bootstrap-datepicker-plus#1]
I have done a pip install. I have done pip install `django-bootstrap-datepicker-plus`. I have added this in my settings

    `INSTALLED_APPS = [    
        'bootstrap_datepicker_plus',
    ]`

also added

    `BOOTSTRAP3 = {
        'include_jquery': True,
    }`

  However it is not working. I have attached image links of how it should display and how it is displaying  at the very end. What am I doing wrong here  

**Forms.py**
   
```
    from django import forms
    from .models import Event
    from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput

    class EventForm(forms.ModelForm):    
        class Meta:
            model = Event
            fields = ('price', 'stock', 'date', 'time_from', 'time_to')
            widgets = {
                'price': forms.NumberInput(), 
                'stock': forms.NumberInput(), 
                'date': DatePickerInput(attrs={'class': 'datepicker'}),# This datepicker is not working 
                'time_from': TimePickerInput(), # These are not working either 
                'time_to': TimePickerInput(),


        def __init__(self, *args, **kwargs):
           super().__init__(*args, **kwargs)
           self.fields['stock'].label = "How many people can attend your event"
           self.fields['price'].label = "How much do members have to pay to attend"
           self.fields['date'].label = "When do you plan to host your event"
           self.fields['time_from'].label = "What time does the event start"
           self.fields['time_to'].label = "What time does the event end"

```
**Template.html**

```
{% load staticfiles %}
        {% load bootstrap3 %}
        {% bootstrap_css %}         {# Embed Bootstrap CSS #}
        {% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
        {% block extrahead %}       {# Extra Resources Start #}
        {{ form.media }}            {# Form required JS and CSS #}
        {% endblock %}              {# Extra Resources End #}
        {% block body %}
    
       
    
     
    
    <div class="form-group row">
         {{field.errors}}
         <form action="{% url 'event:new_event' slug=post.slug %}" method="post" >
             {% csrf_token %}
             {% bootstrap_form form %} 
             <input type="submit" value="Save" class="btn btn-success btn-sm" />
         </form>
    </div>
    {% endblock  %}
```

**Models.py**

 ```
        class Event(models.Model):
              user = models.ForeignKey(User, related_name='seller')
              post = models.ForeignKey(Post, related_name='course')
              price = models.DecimalField(max_digits=6, decimal_places=2)
              stock = models.PositiveIntegerField()
              date = models.DateField()
              time_from = models.TimeField()
              time_to = models.TimeField()
```
        
**Base.html**

 ```
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">[![enter image description here][1]][1]
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
```

**This is how it should work**
https://i.stack.imgur.com/YjSb5.png

**This is how it is now**
https://i.stack.imgur.com/ojmlr.png

What am I doing wrong

**Comment by monim67** [comment]
You should check if there is any JavaScript errors in browser `dev-tools` because as the form is loading in browser there is no error on DJango end. Please inform me if you find any error there in the console and check out the following.

- You are using bootstrap tags in `Template.html`, and adding bootstrap resource files (`js`/`css`) to `Base.html`. You don't need to do both.
- If `Base.html` is your master layout, is `Template.html` extending `Base.html`?
- If you extend `Base.html` in `Template.html` then you already have `jQuery`, then you don't need to set `include_jquery` to `True` (instructions are on `README`).
- You don't need to pass `attrs={'class': 'datepicker'}` to `DatePickerInput`, it works fine without that.
- Please reply here about any JavaScript errors you find in console.

**Comment by samirtendulkar** [comment]
Awesome thanks that worked

**Comment by mj2266** [comment]
```

datepicker-widget.js:3 Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLDocument.<anonymous> (datepicker-widget.js:3)
    at fire (jquery.js:1017)
    at Object.fireWith [as resolveWith] (jquery.js:1127)
    at Function.ready (jquery.js:416)
    at HTMLDocument.DOMContentLoaded (jquery.js:92)




(anonymous) | @ | datepicker-widget.js:3
-- | -- | --
  | fire | @ | jquery.js:1017
  | fireWith | @ | jquery.js:1127
  | ready | @ | jquery.js:416
  | DOMContentLoaded | @ | jquery.js:92
```

I am having similar error as above and this is my Console logs. Can you help?

**Comment by monim67** [comment]
Two possible reasons:
 - Bootstrap JavaScript file is not included in your template.
 - You have multiple jQuery file included in your template ([Read answer to a similar problem on stack-overflow](https://stackoverflow.com/a/48755880/9276329)).

Please check and let me know.

**Comment by mj2266** [comment]
here's my code can you help?
```
INSTALLED_APPS = [
    'bootstrap_datepicker_plus',
    'bootstrap4',
]
```

inside settings.py

`BOOTSTRAP4 = {
    'include_jquery': True,
}`
forms.py:
`


from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from django.contrib.admin import widgets
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class DateInput(forms.DateInput): #ignore this part
    input_type = 'date'
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser

        fields = ('username', 'email', 'gender', 'security_question', 'answer', 'birth_date','bootstrap_date',)
        widgets={
            'birth_date' : DateInput(), #ignore this too
            'bootstrap_date' : DatePickerInput()  #this is the focus part
        }
`
base.html:
`{%load staticfiles%}
<link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}"/>
<html>
<head>
  <meta charset="utf-8">
    {% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}

{% block extrahead %}       {# Extra Resources Start #}
{{ form.media }}            {# Form required JS and CSS #}
{% endblock %}
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>
`
signup.html:
`{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}`

Models.py:
`from datetime import datetime, date

from django.contrib.auth.models import AbstractUser
from django.db import models
import birthday
from djangoyearlessdate.models import YearlessDateField

class CustomUser(AbstractUser):
    # First/last name is not a global-friendly pattern
    name = models.CharField(blank=True, max_length=255)
    M='M'
    F='F'
    GENDER_CHOICES = (
        (M, 'Male'),
        (F, 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    SEC_CHOICE =(
        ('Whats your pet name', 'Whats your pets name'),
        ('Whats your best friends name', 'Whats your best frens name'),
        ('How old are you', 'How old are you'),
    )
    security_question=models.CharField(max_length=200,choices=SEC_CHOICE)

    birth_date = models.DateField(("Birth Date"), default=date.today)

    bootstrap_date=models.DateField(("bootstrap trial"),default=date.today)

    answer=models.CharField(blank=True, max_length=255)

    def __str__(self):
        return self.email`

the error i am getting now
![githubupload](https://user-images.githubusercontent.com/20591733/41862886-c4877f14-78c2-11e8-9011-c07938684e7b.png)
can you help?

**Comment by monim67** [comment]
jQuery is not being loaded, check the first error, `GET ...jquery.. 0 {}`. Check if you can access that link, may be some network or browser-cache corrupt issue. Try:

 - loading the jquery URL in new window, check if it loads completely, hit `Ctrl+F5` if not.
 - clear browser cache.

**Comment by mj2266** [comment]
i just restarted my project and browser and it started working suddenly. You were right jQuery wasnt being loaded. Thanks! I just had one more doubt about how do i verify whether the date I entered is less that Today's date ?

**Comment by monim67** [comment]
'bootstrap_date' : DatePickerInput(
        options={
            "maxDate": "moment().subtract(1,'days')"
        }
    )

More options available on README.

**Comment by mj2266** [comment]
Hey thanks that works! Thank you so much!

**Comment by mj2266** [comment]
Hey do you know how do I sort the stored Birth_dates ? 
Like This is my view function:
```

def birthdaylist(request):
    users=CustomUser.objects.order_by('birth_date')[:]
    context={
        'users':users
    }
    return render(request,'birthdaylist.html',context=context)

```
But what this does is sort it by year as well which is what I don't want. Can you help how to not take year factor in consideration?

**Comment by monim67** [comment]
Check this [stack-overflow](https://stackoverflow.com/q/4236226/9276329) page, stack-overflow has solution for almost every problem, you can even ask your own question on stack-overflow if you don't find what you are looking for.

**Comment by samirtendulkar** [comment]
Dear Munim,

                           It worked I had errors in my django forms which I fixed and things are now working. I will be waiting on the update with the AM and PM on the time picker that would be amazing


Best,

Samir Tendulkar


________________________________

**Comment by samirtendulkar** [comment]
Thank you

Thank you

Than you

thank you


You just solved my my biggest problem with this form


Thank you so so much


Best,

Samir


________________________________

**Comment by mj2266** [comment]
Hey Munim,
I checked out that link and tried but its still not working,
I will show you what i did wait
This is my views.py

```
def birthdaylist(request):
    if(request.user.is_authenticated):
         # this line sorts according to month
        users=CustomUser.objects.order_by(Extract('birth_date','month'))[:]

        # or this code sorts according to year
        #users=CustomUser.objects.order_by('birth_date')[:]

 
        context={
            'users':users
        }
        return render(request,'dashboard/birthdaylist.html',context=context)
    else:
        return redirect('login')
```

I want to sort it according to date, month format so I can display birthday list. Can you help me what should I change? I tried  writing a question on StackOverflow but it was in vain. Here's the link to the question on stack overflow [StackOverflow](https://stackoverflow.com/questions/51124510/django-how-to-sort-datefield-by-order-of-day-month-and-ignoring-year)

**Comment by cmadiam82** [comment]
Hi,

Any idea on how I can do the following?

class ClientForm(forms.Form):
start_date = forms.DateField(widget=DatePickerInput) --> permanent disable past date
start_time = forms.DateField(widget=TimePickerInput) --> permanent disable some hours and temporarily disable past hours

Thanks,
Chester

**Comment by monim67** [comment]
Like [this](https://stackoverflow.com/q/51022722/9276329)?
